name: Boss Approved Run

on:
  push:
    paths:
      - 'approvals/**'     # reagiert auf JEDE Datei in /approvals
  workflow_dispatch:       # manuell aus Actions startbar

permissions:
  contents: write

jobs:
  generate:
    if: "contains(github.event.head_commit.message, 'boss: go')"  # nur bei JA-Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Erzeuge 10 neue Seiten
        run: node ops/generator.js
      - name: Änderungen committen
        run: |
          git config user.name  "auto-bot"
          git config user.email "auto-bot@users.noreply.github.com"
          git add -A
          git commit -m "auto: +10 Seiten (Generator)" || echo "nichts zu committen"
          git push
