name: Boss Approved Run

on:
  push:
    paths:
      # Triggert NUR wenn eine approval-Datei mit "go" erstellt wurde
      - 'approvals/*go.json'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Erzeuge 10 neue Seiten
        run: node ops/generator.js
      - name: Änderungen committen
        run: |
          git config user.name  "auto-bot"
          git config user.email "auto-bot@users.noreply.github.com"
          git add -A
          git commit -m "auto: +10 Seiten (Generator)" || echo "nichts zu committen"
          git push
